vagrantfile:
    target: local
    vm:
        box: puphpet/ubuntu1404-x32
        box_url: puphpet/ubuntu1404-x32
        hostname: dev.local
        memory: '512'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                vflnp_45l0jjr1yq82:
                    host: '2121'
                    guest: '21'
                vflnp_56p6w5ksf21d:
                    host: '2323'
                    guest: '23'
                vflnp_pmu3i010xklc:
                    host: '2525'
                    guest: '25'
                vflnp_y7ym0ukz3em2:
                    host: '6971'
                    guest: '3306'
                vflnp_qhtbpcwmp7zv:
                    host: '6131'
                    guest: '5432'
                vflnp_8jwlo7dxaypr:
                    host: '8080'
                    guest: '80'
                vflnp_swofnowqwv84:
                    host: '4443'
                    guest: '443'
                vflnp_1x9xnn7179ln:
                    host: '4655'
                    guest: '465'
                vflnp_ylkxusqjkdld:
                    host: '10021'
                    guest: '10000'
                vflnp_u7g6dszinwvc:
                    host: '2701'
                    guest: '27017'
                vflnp_jfptinx4z1oa:
                    host: '16379'
                    guest: '6379'
                vflnp_jfptinx4z1ea:
                    host: '3001'
                    guest: '3000'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                showgui: '0'
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vflsf_zg1e4zpzjmzv:
                source: ./php
                target: /usr/share/nginx/php
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
            vflsf_zg1e4zpzjmzp:
                source: ./node
                target: /usr/share/nginx/node
                sync_type: default
                smb:
                    smb_host: ''
                    smb_username: ''
                    smb_password: ''
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                        - .git/
                    auto: 'true'
                owner: www-data
                group: www-data
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - git-core
        - git-flow
        - vim
        - nano
        - mcrypt
        - apt-transport-https
        - ca-certificates
        - build-essential
        - libssl-dev
        - openssl
        - pkg-config
users_groups:
    install: '1'
    groups:
        - admin
    users:
        - 'vagrant:admin:root'
firewall:
    install: '1'
    rules:
        fr_j8g7g6sbzmer:
            port:
                - '10000'
                - '10021'
            priority: '100'
            proto: tcp
            action: accept
cron:
    install: '1'
    jobs: {  }
nginx:
    install: '1'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        php_config:
            server_name: php
            server_aliases:
                - dev.local
            www_root: /usr/share/nginx/php/html
            listen_port: '80'
            index_files:
                - index.html
                - index.htm
                - index.php
            client_max_body_size: 100m
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_port: '443'
            ssl_protocols: ''
            ssl_ciphers: ''
            rewrite_to_https: '1'
            spdy: '1'
            locations:
                nxvl_njm8mpbwe32r:
                    location: /
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                nxvl_ulqvsbytx62e:
                    location: '~ \.php$'
                    autoindex: off
                    try_files:
                        - $uri
                        - $uri/
                        - /index.php$is_args$args
                    fastcgi: '127.0.0.1:9000'
                    fastcgi_index: index.php
                    fastcgi_split_path: '^(.+\.php)(/.*)$'
                    fast_cgi_params_extra:
                        - 'SCRIPT_FILENAME $request_filename'
                        - 'APP_ENV dev'
        node_config:
            server_name: node
            server_aliases:
                - node.local
            www_root: /usr/share/nginx/node/html/
            listen_port: '80'
            client_max_body_size: 100m
            locations:
                nxvl_gejoddlnth13:
                    location: '~* ^.+\.(jpg|jpeg|gif|png|ico)$'
                    autoindex: off
                    try_files: ''
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_alrwbjebth13:
                    location: '~* ^.+\.(css|js)$'
                    try_files: ''
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                nxvl_otbcdsghh13:
                    location: '/'
                    try_files: ''
                    fastcgi: ''
                    fastcgi_index: ''
                    fastcgi_split_path: ''
                    proxy: 'http://127.0.0.1:3000/'
                    proxy_redirect: 'off'
                    proxy_set_header:
                        - 'Host $host'
                        - 'X-Real-IP $remote_addr'
                        - 'X-Forwarded-For $proxy_add_x_forwarded_for'
    proxies: {  }
apache:
    install: '0'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - proxy_fcgi
        - rewrite
    vhosts:
        av_41l3ccur3roc:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            custom_fragment: ''
            ssl: '0'
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
            ssl_protocol: ''
            ssl_cipher: ''
            directories:
                avd_oex0002dgwg7:
                    path: /var/www/awesome
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - 'all granted'
                    custom_fragment: ''
                    files_match:
                        avdfm_tchf9uxovcah:
                            path: \.php$
                            sethandler: 'proxy:fcgi://127.0.0.1:9000'
                            custom_fragment: ''
                            provider: filesmatch
                    provider: directory
php:
    install: '1'
    settings:
        version: '56'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            - memcached
            - curl
            - dev
            - mysql
            - common
            - json
            - gd
            - geoip
            - imagick
            - cgi
            - sqlite
            - memcache
            - mbstring
            - fpm
        pear: {  }
        pecl:
            - pecl_http
            - memcache
            - memcached
            - couchbase
            - mysql
            - mongo
            - redis
            - mcrypt_filter
            - yaml
            - python
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        date.timezone: UTC
        upload_max_filesize: '100'
        post_max_size: '100'
    fpm_ini:
        error_log: /var/log/php-fpm.log
    fpm_pools:
        phpfp_q76p10otaqso:
            ini:
                prefix: www
                listen: '127.0.0.1:9000'
                security.limit_extensions: .php
                user: www-user
                group: www-data
    composer: '1'
    composer_home: ''
xdebug:
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
blackfire:
    install: '0'
    settings:
        server_id: ''
        server_token: ''
        agent:
            http_proxy: ''
            https_proxy: ''
            log_file: stderr
            log_level: '1'
        php:
            agent_timeout: '0.25'
            log_file: ''
            log_level: '1'
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: v0.19.0
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions: {  }
python:
    install: '1'
    packages: {  }
    versions: {  }
nodejs:
    install: '1'
    npm_packages:
        - express
        - mongoose
        - forever
        - socket.io
        - mocha
        - sinon
        - chai
        - jasmine
        - colors
        - bower
        - passport
        - gulp
        - grunt
        - gulp-uglify
        - grunt-cli
        - express-generator
        - react
        - mongodb
        - yo
        - q
        - underscore
        - browserify
        - gulp-scss
        - bcrypt
        - gulp-imagemin
        - angular
        - ejs
        - handlebars
        - cron
        - gulp-less
        - csv
        - xlsx
        - d3
        - babel
        - googleapis
        - phonegap
        - squel
        - pm2
        - nodemon
        - browserify
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings: {  }
    server_ini:
        hhvm.server.host: 127.0.0.1
        hhvm.server.port: '9000'
        hhvm.log.use_log_file: '1'
        hhvm.log.file: /var/log/hhvm/error.log
    php_ini:
        display_errors: On
        error_reporting: '-1'
        date.timezone: UTC
mysql:
    install: '1'
    settings:
        version: '5.6'
        root_password: '123'
        override_options: {  }
    adminer: 0
    users:
        mysqlnu_8v68rnp71jkk:
            name: dbuser
            password: '123'
    databases:
        mysqlnd_0080rlsu56ou:
            name: dbname
            sql: ''
    grants:
        mysqlng_n5v902x7euud:
            user: dbuser
            table: '*.*'
            privileges:
                - ALL
postgresql:
    install: '1'
    settings:
        global:
            encoding: UTF8
            version: '9.3'
        server:
            postgres_password: '123'
    databases: {  }
    users: {  }
    grants: {  }
    adminer: 0
mongodb:
    install: '1'
    settings:
        auth: 1
        bind_ip: 127.0.0.1
        port: '27017'
    databases:
        mongodbnuad_m1jmkjiulr24:
            name: dbname
            user: vagrant
            password: '123'
redis:
    install: '1'
    settings:
        conf_port: '6379'
sqlite:
    install: '1'
    adminer: 0
    databases: {  }
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
rabbitmq:
    install: '0'
    settings:
        port: '5672'
    users: {  }
    vhosts: {  }
    plugins: {  }
elastic_search:
    install: '0'
    settings:
        version: 1.4.1
        java_install: true
solr:
    install: '0'
    settings:
        version: 4.10.2
        port: '8984'

